"""empty message

Revision ID: 649db9fe01bc
Revises: a477ce1b4391
Create Date: 2021-06-10 13:45:46.385406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '649db9fe01bc'
down_revision = 'a477ce1b4391'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
